# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 596dbaaf6413a2c4c58df42c454da1bcc6ac5945245ff76c5a39753e359f2866daadeb191fac8fe2c308878f9bb752ee9bf164853fd2419c272d419ee0ebe8a9

test:
  secret_key_base: adc65528a468386d922bdc62a5eb569a7dacdbcf753ae4a36d84b34f0590b88932fd8abe4071e7bb9d5e1da24304892f7d3f4cd553da85057a3dfed7fac39490

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
